version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9

    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build

    test:
      docker: 
        - image: circleci/node:8.9
      steps:
        - run: echo "testing stuff"
        - run: npm install
        - run: npm test

      - run:
          name: Print the Current Time
          command: date